version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=students_nsgx

  studentapict:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  data:
